# Generated by Django 4.2.9 on 2024-01-18 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='hecho',
        ),
        migrations.AddField(
            model_name='tareas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('en_pruebas', 'En Pruebas'), ('estancado', 'Estancado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='tareas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
